const SOURCE_REQUEST = "SOURCE_REQUEST";
const SOURCE_SUCCESS = "SOURCE_SUCCESS";
const SOURCE_FAIL = "SOURCE_FAIL";

const CHANGE_THEME = "CHANGE_THEME";

export { SOURCE_REQUEST, SOURCE_SUCCESS, SOURCE_FAIL, CHANGE_THEME };
