const SOURCE_REQUEST = "SOURCE_REQUEST";
const SOURCE_SUCCESS = "SOURCE_SUCCESS";
const SOURCE_FAIL = "SOURCE_FAIL";
const SOURCE_FAV = "SOURCE_FAV";
const SOURCE_SELECT = "SOURCE_SELECT";

const CHANGE_THEME = "CHANGE_THEME";

const HEADLINE_REQUEST = "HEADLINE_REQUEST";
const HEADLINE_REQUEST_SUCCESS = "HEADLINE_REQUEST_SUCCESS";
const HEADLINE_REQUEST_FAIL = "HEADLINE_REQUEST_FAILS";

export {
  SOURCE_REQUEST,
  SOURCE_SUCCESS,
  SOURCE_FAIL,
  CHANGE_THEME,
  SOURCE_FAV,
  HEADLINE_REQUEST,
  HEADLINE_REQUEST_SUCCESS,
  HEADLINE_REQUEST_FAIL,
  SOURCE_SELECT,
};
